
modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="insect_hearts"
version="1.0.0"
displayName="Insect Hearts Lava Door"
authors="Insect"
description='''Standalone lava door mod.'''
[[dependencies.insect_hearts]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.insect_hearts]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
